//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genero
    {
        public Genero()
        {
            this.Restaurante = new HashSet<Restaurante>();
        }
    
        public int IDGenero { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Restaurante> Restaurante { get; set; }
    }
}
