//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauranteBDEntities : DbContext
    {
        public RestauranteBDEntities()
            : base("name=RestauranteBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bairro> Bairro { get; set; }
        public DbSet<Genero> Genero { get; set; }
        public DbSet<Restaurante> Restaurante { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
